# Generated by Django 4.2 on 2023-10-12 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_confirm_privacy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='confirm_privacy',
        ),
    ]
